#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=$1 python2 examples/StackPointerParser.py \
    --mode FastLSTM \
    --no_CoRNN \
    --num_epochs 2000 \
    --batch_size 32 \
    --decoder_input_size 256 \
    --hidden_size 300 \
    --trans_hid_size 2048 \
    --encoder_layers 6 \
    --d_k 64 \
    --d_v 64 \
    --decoder_layers 1 \
    --pos_dim 300 \
    --char_dim 300 \
    --num_filters 100 \
    --arc_space 512 \
    --type_space 128 \
    --opt adam \
    --learning_rate 0.0001 \
    --decay_rate 0.75 \
    --epsilon 1e-4 \
    --coverage 0.0 \
    --gamma 0.0 \
    --clip 5.0 \
    --schedule 20 \
    --double_schedule_decay 5 \
    --use_warmup_schedule \
    --check_dev 5 \
    --p_in 0.2 \
    --p_out 0.2 \
    --p_rnn 0.2 0.1 0.2 \
    --unk_replace 0.5 \
    --label_smooth 1.0 \
    --beam 1 \
    --prior_order inside_out \
    --grandPar \
    --sibling \
    --freeze \
    --pos \
    --pool_type weight \
    --multi_head_attn \
    --rel_aware \
    --clip_dist 2 \
    --num_head 8 \
    --word_embedding word2vec \
    --word_path 'vocab/alphabets/joint_embed.vec' \
    --char_embedding random \
    --punctuation 'PUNCT' 'SYM' \
    --train "data2.2/en_ewt-ud-train.conllu" \
    --dev "data2.2/en_ewt-ud-dev.conllu" \
    --test "data2.2/de_gsd-ud-test.conllu" \
    --vocab_path 'vocab/' \
    --model_path 'models/parsing/stack_ptr_en_de_rnn/' \
    --model_name 'network.pt'
